
sudo: required

language: go
go:
  - "1.10"

services:
  - docker

install:
  - make install

script:
  - make lint
  - make build
  - make test_and_coverage

after_success:
  - bash scripts/docker_build_and_push.sh

cache:
  directories:
    - "vendor"

notifications:
  email:
    on_success: never
    on_failure: change
